[package]
name = "dontsleep"
version = "0.1.0"
authors = ["Siddharth Doshi <sidoshi510@gmail.com>"]
edition = "2018"

[lib]
name = "dontsleep"

[[bin]]
name = "dontsleep"

[dependencies]
core-graphics = "0.22.0"
tokio = { version = "1.14.0", features = ["full"] }
